### PR TITLE
Add the awesome laravel key generate command

### PR DESCRIPTION
**Pull request by abstractFlo**
Please add this PR for enable the awesome command for generating app keys.

I have changed a little bit from the laravel version. No need for app.php in config folder. Overwrite APP_KEY in .env file easy

### CODE REVIEW

**Comment by jbrooksuk** [comment]
:+1: I was just about to do the same thing.

**Comment by GrahamCampbell** [comment]
You must use spaces for indentation.

**Comment by GrahamCampbell** [comment]
Also, I'm :-1: on adding anything more to Lumen. It's supposed to be really light and basic.

**Comment by abstractFlo** [comment]
GrahamCampbell i can't understand your problem. Ist only a simple helper for generating the Key. I think all people love this. 

no key you have to come up with and has therefore not always temptation to use the same.

**Comment by GrahamCampbell** [comment]
@abstractFlo My point is that if people want this, they should probably be using Laravel, not Lumen.

**Comment by abstractFlo** [comment]
What? Thats not the point. It's a simple command. Not more, Lumen is awesome and only for this fu... Command i must use laravel? Not really

**Comment by GrahamCampbell** [comment]
@abstractFlo It's not just this command. We have to draw a line somewhere, or everything from Laravel will end up in Lumen because it's "cool".

**Comment by abstractFlo** [comment]
that's the point is not, it's still just a matter of simple, quickly and safely to generate a key app. no more and no less

but if you mean that everyone who wants to use this command lumen, not to use, then it is so.

I can not understand

**Comment by GrahamCampbell** [comment]
My issue is with us registering a command that is only useful once.

**Comment by abstractFlo** [comment]
yes, and thats the point. Only useful once, for secure session, cookies, crypt.....

**Comment by jbrooksuk** [comment]
What if this was a package?

**Comment by GrahamCampbell** [comment]
It might be cool to get this integrated into the illuminate installer perhapse?

**Comment by abstractFlo** [comment]
@jbrooksuk thats not my opinion. it's a small command. i think this is a base feature of a secure application. Helps people to get secure keys....

**Comment by jbrooksuk** [comment]
@GrahamCampbell I like that idea.

@abstractFlo the problem with adding another command (just like #23) is that the IOC has to register another class, it adds overhead.

**Comment by abstractFlo** [comment]
It's your choice, i think there is no more overhead with this command.

**Comment by jbrooksuk** [comment]
But of course there is overhead. It's more to be loaded in. Whilst they may be light classes, if you keep adding them, then it's not light anymore :)

**Comment by tommymarshall** [comment]
Maybe on `post-install` grab the contents of a randomly generated key from a service/app that is also running Lumen? (key.lumen.laravel.com) How meta would that be ;)

**Pull request closed without merging**
