### PR TITLE
Add support for UrlRoutable to route()

### PR DESCRIPTION
**Pull request by jenssegers**
I noticed that `route()` does not support the `UrlRoutable` interface. This is a first attempt to add it.

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
5.0 is closed for changes.

**Comment by GrahamCampbell** [comment]
Whoops. Missread the name of the repo...

**Comment by jenssegers** [comment]
Should I do the PR on master?

**Comment by GrahamCampbell** [comment]
No.

**Comment by jenssegers** [comment]
Cheers! 🍻

**Pull request merged**
