### PR TITLE
[6.x] Updated the PSR17 RequestFactory and PSR7 Response classes to use Nyh…

### PR DESCRIPTION
**Pull request by boywijnmaalen**
Updated the PSR17 RequestFactory and PSR7 Response classes to use Nyholm/Psr7 version.

If Nyholm/Psr7 is not present, default back to Symfony/Bridge/[..]/DiactorosFactory & Zend/Diactoros/Response respectively

fixes laravel/lumen-framework#1027

### CODE REVIEW

**Comment by boywijnmaalen** [comment]
@driesvints; I changed the author email address of the commit (accidentally used wrong 'email address')

**Comment by GrahamCampbell** [comment]
Please can you make this the same as what the laravel/framework code does.

**Comment by boywijnmaalen** [comment]
@GrahamCampbell I was unaware this was already taken care of laravel/framework. Thanks for the heads up. I've amended the commit as suggested

**Comment by GrahamCampbell** [comment]
The composer.json suggest needs fixing too. Could you PR that?

**Comment by boywijnmaalen** [comment]
@GrahamCampbell 

The `Zend\Diactoros` namespace references package `zendframework/zend-diactoros`. This package however has been archived. An alternative is mentioned in the readme file, should the alternative package be suggested in laravel/lumen-framework composer.json (and with that a class reference change from 'Zend\Diactoros' to 'Laminas\Diactoros') or should I stick with suggesting the archived `zendframework/zend-diactoros` package.

**Comment by GrahamCampbell** [comment]
Match laravel 6.x. Please could you also update 7.x to latch laravel 7.x (code and composer).

**Comment by boywijnmaalen** [comment]
@GrahamCampbell apologies for asking again, but I can't find a 7.x branch anywhere, I've checked laravel/laravel, laravel/laravel-framework, laravel/lumen, laravel/lumen-framework. Is it possible this branch isn't visible somehow?

**Comment by GrahamCampbell** [comment]
It's called master. :)

**Comment by GrahamCampbell** [comment]
I've made the changes now, in https://github.com/laravel/lumen-framework/pull/1030 and https://github.com/laravel/lumen-framework/pull/1031.

**Comment by boywijnmaalen** [comment]
@GrahamCampbell; apologies for the late reply, I see you've updated the code yourself, thanks!

**Comment by YassineChe** [comment]
Same issue,
Did you find a solution ?

**Comment by boywijnmaalen** [comment]
@YassineChe, yes a fix was added by GrahamCambell on Feb 1st. Run `composer update laravel/lumen-framework` to update your application with the latest lumen-framework dependency (please note this was added for lumen-framework 6.x or 7.x).

**Comment by YassineChe** [comment]
@boywijnmaalen i've solved this by installing the previous version of `psr-http-message-bridge`, but this solution isn't practical, may occur some issues in near future.
Unfortunately i'm not using lumen, i'm suing the laravel 7.0, this error appeared when i added a package called `sfelix-martins/passport-multiauth` based on Laravel Passport.
Any new suggestions ?

**Comment by boywijnmaalen** [comment]
@YassineChe;

Which version of `passport-multiauth` are you using? I'm aksing since version [v7.0.0](https://github.com/sfelix-martins/passport-multiauth/commit/f4766428e28abe05cc8307415fa16389c56af965) was made compatible with v2.x of `symfony/psr-http-message-bridge` (in the latter class PsrHttpFactory was added in favor of the deprecated DiactorosFactory class). I'd recommend upgrading to `passport-multiauth:v7.x` and `symfony/psr-http-message-bridge:v2.x` if possible, as using `symfony/psr-http-message-bridge:v2.x` is the correct and future-proof way forward.

**Comment by YassineChe** [comment]
@boywijnmaalen ,
You're absolutely right, i didn't realize that i was working with the older version (6.0) of this package,
since i runned the command (composer install ...) i thought that will pull the latest version until you warned me.

I did update `passport-multiauth` and `psr-http-message-bridge` to the latest versions, and i pushed these updates to the repository, everything works fine.
Thank you so much for this ticket, you saved my day.

**Pull request merged**
