### PR TITLE
Replace storage_path with database_path helper

### PR DESCRIPTION
**Pull request by jovib**
According to the docs, the sqlite database should be located within the "database" folder.

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
The docs are out of date and need updating.

**Comment by GrahamCampbell** [comment]
Oh, wait, I see. We just forgot to update this on Lumen, and only updated it on Laravel.

**Comment by GrahamCampbell** [comment]
:+1: then

**Comment by jovib** [comment]
Okay!! don't worry that much about this as I easily can change it myself.

**Comment by GrahamCampbell** [comment]
I meant to re-open this, sorry.

**Pull request merged**
