### PR TITLE
[5.3] Missing trans function

### PR DESCRIPTION
**Pull request by forzadraco**
please help to add missing helper function trans

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
I don't think it's "missing". I think it's not included by design?

**Comment by GrahamCampbell** [comment]
Lumen is not designed to render views, where I assume you're using that. It's designed to be used to implement json http apis and the like.

**Comment by GrahamCampbell** [comment]
For real applications, Laravel is recommended, not Lumen.

**Comment by forzadraco** [comment]
Hi Graham,
I understand, but I'm not use view. I'm using lumen for API, there is no view. only json is return.
we need trans function to return response language based on client request. 
for example It's better to not store your localization language file at mobile apps. you need return the error messages in Api level not in Apps level. 

if lumen doesn't have localization feature it is a pity. @taylorotwell what do you think ?

**Comment by GrahamCampbell** [comment]
> if lumen doesn't have localization feature it is a pity

Well, given that this helper works, localization is clearly possible. I was just saying that the helper was probably omitted in order to indicate in an opinionated way to avoid using it.

**Comment by taylorotwell** [comment]
Thanks. For future reference please respect the conventions of the framework. This entire file had methods in alphabetical order, etc.

**Pull request merged**
