### PR TITLE
Enable ENV configuration of all db

### PR DESCRIPTION
**Pull request by jakubriedl**
enables configuration of DB_SCHEMA, DB_CHARSET and DB_COLLATION using ENV

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
:-1:

**Comment by jakubriedl** [comment]
why not?
This is very important for us to be able to configure DB_SCHEMA for pgsql. Because every micro-service uses different.

**Comment by GrahamCampbell** [comment]
You can configure it, just not using env.

**Comment by GrahamCampbell** [comment]
I think if you want to use env, then use it yourself. Doesn't belong here as a default for everyone IMO.

**Comment by jakubriedl** [comment]
Configuring database schema is the same as setting database name. It is basic argument to connecting to postgres. And anyone who uses multiple schemas in postgres will need it.

**Comment by Nielsdv** [comment]
Hi GrahamCampbell.

Then please remove the hardcoded "public" in schema.
Not only is the mention of the default schema optional in all schema powered databases (so why define it ?) it is also the wrong place to define it, since Postgresql configuration is in charge of the default through the search_path parameter, which in many cases is overriden.

So if this setting does not belong in the env file, it should not contain the arbitrary value of "public" as well.

**Pull request closed without merging**
