### PR TITLE
Compatibility with Lumen running on subdirectory

### PR DESCRIPTION
**Pull request by estudiogenius**
The Application method getPathInfo() do not undestend when we are running on subdirectory... the Request do!

### CODE REVIEW

**Comment by ptcong** [comment]
This fix take ~10ms~ 
I have submit a PR #21 that following criteria of Lumen.

**Comment by estudiogenius** [comment]
Cool!

**Comment by taylorotwell** [comment]
Just pass a request via the run() method of your index.php file.

**Comment by pvormittag** [comment]
I've run into this situation as well. Many of my team members develop locally within a single shared host, separating projects with sub-directories.

@taylorotwell As you mention, passing a request to run() fixes the issue, however it seems odd to pass  $app its own request reference?

```php
/*
|--------------------------------------------------------------------------
| Run The Application
|--------------------------------------------------------------------------
|
| Once we have the application, we can handle the incoming request
| through the kernel, and send the associated response back to
| the client's browser allowing them to enjoy the creative
| and wonderful application we have prepared for them.
|
*/

$app->run($app->request);
```

**Comment by ptcong** [comment]
`$app->request` will capture information of the current request.

**Pull request closed without merging**
