### PR TITLE
[5.8] Add the eventsAreCached method.

### PR DESCRIPTION
**Pull request by lloricode**
lumen does not have ability with this, so let add deafult value as `false`

same here https://github.com/laravel/lumen-framework/pull/792

lumen does not support caching

### CODE REVIEW

**Comment by driesvints** [comment]
@lloricode can you fix the styleci warning?

**Comment by lloricode** [comment]
Hi @driesvints, @taylorotwell,

Thanks for merging, then can we have this with tag?

Best regards

**Comment by driesvints** [comment]
@lloricode Tuesday's are release days so probably today.

**Comment by lloricode** [comment]
@driesvints thank you

**Pull request merged**
