### PR TITLE
Create CHANGELOG.md

### PR DESCRIPTION
**Pull request by jaoued**
Started at v5.1.2 - 2015-07-12

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
This is just adding more to maintain.

**Comment by jaoued** [comment]
What? This is a mandatory information for any open source project and it's maintain by community too!

Please reconsider your decision.

**Comment by GrahamCampbell** [comment]
> What? This is a mandatory information for any open source project and it's maintain by community too!

Laravel doesn't have a change log.

**Comment by GrahamCampbell** [comment]
Infact, the decision was already taken to remove the change log from laravel because it was never updated by the community, or by anyone for that matter.

**Comment by jaoued** [comment]
That's why i decided to contribute to create one for Lumen because i love this micro-framework! And this is a responsability to any one who contribute to maintain a changelog.

**Comment by GrahamCampbell** [comment]
> is a responsability to any one who contribute to maintain a changelog.

That never happens though, and you know it.

**Comment by jaoued** [comment]
Don't be pessimistic, Laravel's world has a great future and the community will continue to grow over the world.

We must ensure that this continues, even if it requires an effort. it is vital to invest more time in quality. Otherwise it will eventually no longer be used.

Since LTS version 5.1. Laravel/Lumen is not intended for lonely developers for small projects but for businesses and for ambitious projects. Must ensure that their trust is not betrayed.

Regards.

**Comment by GrahamCampbell** [comment]
> Don't be pessimistic

I'm just being realistic. I've been watching contributions over the last year, and 90% of the time, change logs are forgotten about in the other laravel repos.

**Comment by taylorotwell** [comment]
We will indeed need a good way to manage this, as contributors themselves will never do it themselves and it will clog up the whole pipeline trying to make everyone do it. Personally I would rather just tag new features with a label on GitHub as they are PR'd so I can construct the change log myself at the end of the release cycle.

**Comment by jaoued** [comment]
@taylorotwell ok, that's good idea. it's better than nothing.

**Pull request closed without merging**
