### PR TITLE
Change controller validate helper method to behave like Laravel (#1247)

### PR DESCRIPTION
**Pull request by MattApril**
#1247

### CODE REVIEW

**Comment by driesvints** [comment]
Tests are failing here.

**Comment by MattApril** [comment]
Whoops, I forgot that I overwrote my own exception handler. Looks like Lumen's default handler excepts the response to be set on the ValidationException. Fixed.

**Comment by taylorotwell** [comment]
Would this break existing applications?

**Comment by MattApril** [comment]
Yes, it would cause a breaking change if anyone overwrote the protected extractInputFromRules or throwValidationException methods. I just updated it to use those methods if they are defined.

**Comment by halloei** [comment]
This broke my application. I'm not overwriting `extractInputFromRules()` and `throwValidationException()`, I'm calling them directly from my controller.

**Comment by driesvints** [comment]
We're reverting this.

**Comment by MattApril** [comment]
Hmm, that was an unfortunate oversight. Sorry about that.

I think this should be released as a breaking change in the next major version though. The current validation is not behaving as expected.

**Pull request merged**
