### PR TITLE
[5.9] Add custom storage path support

### PR DESCRIPTION
**Pull request by pavinthan**
Make storage path customizable
It's help to deploy Lumen application to sever-less solution like AWS Lamda

Please provide your feedbacks and if it's wrong implementation please make customizable storage

### CODE REVIEW

**Comment by pavinthan** [comment]
@GrahamCampbell, may  know? it won't break anything then why it's target to 5.9

**Comment by GrahamCampbell** [comment]
Because you sent it to the 5.9 branch?

**Comment by pavinthan** [comment]
Woops, I have created a PR https://github.com/laravel/lumen-framework/pull/920 to target 5.8, may I know what can I do this PR ?

**Comment by driesvints** [comment]
I'll just close this one. All changes from 5.8 will be merged into master.

**Pull request closed without merging**
