### PR TITLE
Re-add maintenance mode.

### PR DESCRIPTION
**Pull request by jbrooksuk**
Maintenance mode now works again. The actual [lumen](https://github.com/laravel/lumen) app just needs the middleware adding for `CheckForMaintenanceMode`.

### CODE REVIEW

**Comment by jbrooksuk** [comment]
I love that this was partially implemented.

**Comment by ptcong** [comment]
Should re-add `app:name` too ?

**Comment by jbrooksuk** [comment]
Yeah, but in a separate commit.

**Comment by taylorotwell** [comment]
I'm purposefully keeping these types of things out of the repo. Also, something like Envoyer is really the better way to go as even maintenance mode will give you down time.

**Comment by GrahamCampbell** [comment]
This is something you can add to your own application if you want to anyway. :)

**Comment by jbrooksuk** [comment]
That's how it started out for me :)

**Pull request closed without merging**
