### PR TITLE
Access current route in controller/route middleware using request->route() method + test

### PR DESCRIPTION
**Pull request by michalkvasnicak**
Added tests too.

### CODE REVIEW

**Comment by taylorotwell** [comment]
This still isn't right. This would resolve the request on every request which is not what we want. There is another way to fix this.

**Comment by michalkvasnicak** [comment]
@taylorotwell I found a problem, there is a line https://github.com/laravel/lumen-framework/blob/5.0/src/Application.php#L1081

This line is preventing application to call registerRequestBindings. If you comment this line out, there is no need to make request as in this pullrequest and tests still passes.

**Comment by taylorotwell** [comment]
​Commenting that out will break other things.​

**Comment by michalkvasnicak** [comment]
Can I ask you what it will break? Because it will be set to `true` here https://github.com/laravel/lumen-framework/blob/5.0/src/Application.php#L363 on `make()` call.

**Pull request closed without merging**
