### PR TITLE
[7.x] Switched to Symfony 5

### PR DESCRIPTION
**Pull request by GrahamCampbell**

### CODE REVIEW

**Comment by driesvints** [comment]
@GrahamCampbell took the liberty of updating your pr

**Comment by GrahamCampbell** [comment]
Thanks. I should have marked this as WIP originally. :)

**Comment by GrahamCampbell** [comment]
Alright. This is ready now I think.

**Comment by GrahamCampbell** [comment]
Ping. :)

**Comment by GrahamCampbell** [comment]
Just rebased this after the phpdotenv change was merged.

**Pull request merged**
