### PR TITLE
[6.x] Fix the required Cache implementation parameter and db:wipe command registration

### PR DESCRIPTION
**Pull request by lvismer**
Fixed the required Cache parameter for the QueueRetryCommand, QueueRestartCommand and QueueWorkCommand instantiated objects.

Register the db:wipe command as it is used by migrate:fresh

### CODE REVIEW

**Comment by driesvints** [comment]
Thanks!

**Comment by driesvints** [comment]
released v6.0.1 with this

**Comment by lvismer** [comment]
The commit with changes to registerQueueRetryCommand, registerQueueRestartCommand and registerQueueWorkCommand was not merged. Apologies if that is an error on my side.

**Comment by driesvints** [comment]
Released v6.0.2

**Pull request merged**
