### PR TITLE
Allow setting application base path

### PR DESCRIPTION
**Pull request by tshafer**

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
I think this has been rejected already?

**Comment by tshafer** [comment]
Any idea why?

**Comment by GrahamCampbell** [comment]
Lumen doesn't support running in a subdirectory, as far as I know...

**Comment by GrahamCampbell** [comment]
Oh crap. Badly misread that. Sorry...

**Comment by tshafer** [comment]
I got it running using this function, just thought it would be useful. I can always extend the application class.

**Comment by tshafer** [comment]
I got it working using the function, I extended Application the class for now to add the function.

**Comment by GrahamCampbell** [comment]
Ok. Taylor will review this shortly. :)

**Comment by tshafer** [comment]
Thanks!

**Comment by taylorotwell** [comment]
Have a fix for this coming.

**Pull request closed without merging**
