### PR TITLE
[5.2] Add Hash facade.

### PR DESCRIPTION
**Pull request by lukeed**
Maybe I'm missing something, but neither `Hash` nor `bcrypt` are available within Lumen 5.2

Is there another recommended method or replacement? If so, apologies.

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
:-1: from me. Lots of aliases were intetionally missed out.

**Comment by GrahamCampbell** [comment]
Lumen is meant be be **really** light.

**Comment by lukeed** [comment]
Right, figured. 

Still thought there'd be a base encryptor --- but it's always easy to add manually.

**Comment by GrahamCampbell** [comment]
I'll never understand what's so wrong with `use Illuminate\Support\Facades\Hash;`. ;)

**Comment by lukeed** [comment]
Nothing :stuck_out_tongue_winking_eye:

**Comment by GrahamCampbell** [comment]
To be fair, it could be worse...

image

Screenshot from an actual class from a real application...

**Comment by lukeed** [comment]
:see_no_evil: :skull:

**Comment by GrahamCampbell** [comment]
Anyway, it's up to Taylor to ultimately decide if this is getting merged, so it might still go through anyway. ;)

**Comment by GrahamCampbell** [comment]
I only really find aliases useful when inside views, say using `Str::`.

**Comment by taylorotwell** [comment]
Intentionally left out.

**Pull request closed without merging**
