### PR TITLE
[5.7] Fix overwriting the Application class

### PR DESCRIPTION
**Pull request by driesvints**
See https://github.com/laravel/lumen-framework/pull/840. Added a test to verify the correct behavior.

### CODE REVIEW

**Comment by crynobone** [comment]
But can Lumen resolve to `App\Application` when you try to use dependency injection by type-hinting `Laravel\Lumen\Application`?

**Comment by crynobone** [comment]
I would say reverting the changes is still the best bet, anyone who want to extends Application should be able to alias it under `bootstrap.php`.

**Comment by driesvints** [comment]
> But can Lumen resolve to App\Application when you try to use dependency injection by type-hinting Laravel\Lumen\Application?

@crynobone yes, that's what the tests proves. 

> I would say reverting the changes is still the best bet, anyone who want to extends Application should be able to alias it under bootstrap.php.

But with this PR you wouldn't have to do that. What makes you think we should revert this?

**Comment by crynobone** [comment]
Sorry I got confuse with what this trying to revert to vs what #847.

**Comment by driesvints** [comment]
No worries :)

**Pull request merged**
